name: Reek

on: push

jobs:
  reek:
    name: Reek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: gem install reek --no-doc
      - run: reek .
      - name: Generate reek json
        run: reek --format json > reek.json
        if: ${{ failure() }}
      - uses: duderman/reek-annotate-action@v0.1.0
        if: ${{ failure() }}
